FreeSky/FreeSky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('api/', include('api.urls')),
	path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
	path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FreeSky/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('search', views.SearchAPI.as_view(), name='search'),
	path('notes/update/<int:pk>', views.UpdateNoteAPI.as_view(), name='notes'),
]

FreeSky/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import CreateContentNote, ContentPreviewsView, ContentView, DeleteContentNote


urlpatterns = [
    path('', ContentPreviewsView.as_view(), name='content-list'),
	path('note/<int:note_pk>/', ContentView.as_view(), name='note'),
	path('note/<slug:slug>/<int:note_pk>/', ContentView.as_view()),
	# path('note/<slug:slug>/',ContentView.as_view(), name='note'),
	# path('new/', CreateContentNote.as_view(), name='new-post'),
	path('note/settings/delete/note/<int:note_pk>/', DeleteContentNote.as_view(), name='delete_note'),
]

FreeSky/social/models.py
import os
from datetime import datetime
from django.shortcuts import reverse
from django.db import models
from django.contrib.sessions.models import Session
from user.models import User
from locations.models import Location
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


def preview_img_upload_to(instance, filename):
	return f'notes/preview_images/{datetime.now().date().strftime("%Y/%m/%d")}/{filename}'

class Tag(models.Model):
	name = models.TextField(_('Тег'), unique=True, primary_key=True)

	def __str__(self):
		return f'{self.name}'

class Note(models.Model):
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	content = RichTextUploadingField(_('Содержание'), null=True, blank=False)
	likes = models.ManyToManyField(User, related_name='like_set', blank=False)
	views = models.ManyToManyField(Session, related_name='view_set', blank=False)
	publish_date = models.DateTimeField(_('Дата публикации'), default=datetime.now())

	def __str__(self) -> str:
		return f'{self.user_id}, {self.publish_date}'

	def get_author(self):
		return f'{self.user_id.get_full_name()}'

	def add_view(self, session):
		self.views.add(session)
		self.save()
		return self.views.count()

	def add_like(self, user):
		self.likes.add(user)
		self.save()
		return self.likes.count()

class Article(Note):
	title = models.TextField(_('Название поста'), unique=True, max_length=80)
	preview_image = models.ImageField(_('Превью'), upload_to=preview_img_upload_to)
	tags = models.ManyToManyField(Tag, blank=True)
	location = models.ManyToManyField(Location, blank=True)

	class Meta:
		verbose_name = 'Пост'
		verbose_name_plural = 'Посты'
	
	def get_absolute_url(self):
		return reverse('note', kwargs={'note_pk': self.pk})
	
	def get_delete_url(self):
		return reverse('delete_note', kwargs={'note_pk': self.pk})
	
	def __str__(self) -> str:
		return f'{self.title}'

class AdminArticle(Article):
	slug = models.SlugField(_('URL-заголовок'), max_length=255, db_index=True)

	class Meta:
		verbose_name = 'Пост администратора'
		verbose_name_plural = 'Посты администраторов'
	
	def get_author(self):
		return 'FreeSky'

	def get_absolute_url(self):
		return reverse('note', kwargs={'slug': self.slug,'note_pk': self.pk})

class CommentNote(Note):
	post = models.ForeignKey(Note, on_delete=models.CASCADE, related_name='note_comment_set')
	
	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

FreeSky/social/forms.py
from django import forms
from django.db.models import Q
from locations.models import Location
from locations.models import Country, Settlement
from social.models import Article, CommentNote, Tag
from social.fields import TagField, CharToObjField, ChoiceTextInput
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from user.services.form_manager import NoteFormBehavior


class SearchArticleForm(forms.Form):
	class Choice:
		date_choice = (('-publish_date', 'Сначала новое'), ('publish_date', 'Сначала старое'))
		populatity_choice = (('likes', 'Больше всего лайков'), ('views', 'Больше всего просмотров'), ('popularity', 'Наибольшая активность'))
		author_choice = (('all', 'Все посты'), ('user', 'Посты Пользователей'), ('admin', 'Посты FreeSky'))

	text = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':''}))
	author = forms.ChoiceField(choices=Choice.author_choice, required=False)
	populatity = forms.ChoiceField(choices=Choice.populatity_choice, required=False)
	publish_time = forms.ChoiceField(choices=Choice.date_choice, required=False)
	
	location = CharToObjField(
		model=Location,
		queryset=Location.objects.filter(~Q(name='NaN') & Q(country__isnull=False) | Q(settlement__isnull=False)),
		widget=ChoiceTextInput(
			datalist=Location.objects.filter(~Q(name='NaN') & Q(country__isnull=False) | Q(settlement__isnull=False)),
			attrs={'list': 'country_set'}
		),
		required=False
	)

	@classmethod
	def keys(cls):
		return cls.__dict__['base_fields'].keys()


class ContentNoteForm(forms.ModelForm, NoteFormBehavior):
	tags = TagField(queryset=Tag.objects.all(), widget=ChoiceTextInput(datalist=Tag.objects.all(), attrs={'list': 'tags_set'}), required=False)
	country = CharToObjField(model=Country, queryset=Country.objects.exclude(code='lNaN'), widget= ChoiceTextInput(datalist=Country.objects.all(), attrs={'list': 'country_set'}), required=False)
	settlement = CharToObjField(model=Settlement, queryset=Settlement.objects.all(), widget= ChoiceTextInput(datalist=Settlement.objects.all(), attrs={'list': 'settlement_set'}), required=False)
	class Meta:
		model=Article
		fields=('user_id', 'preview_image', 'title', 'content', 'tags')
		widgets = {
			'user_id': forms.HiddenInput(),
			'title': forms.TextInput(attrs={'class':'content-form'}),
			'slug': forms.TextInput(attrs={'class':'content-form', 'label': 'URL-заголовок'}),
		}
	
	def save(self, commit: bool = True):
		instance = super().save(commit)
		if self.cleaned_data['country']:
			instance.location.add(self.cleaned_data['country']) 
		if self.cleaned_data['settlement']:
			instance.location.add(self.cleaned_data['settlement'])
		return instance
	

class CommentNoteForm(forms.ModelForm):
	content = forms.CharField(label='', widget=CKEditorUploadingWidget(config_name='comment'))
	class Meta:
		model=CommentNote
		fields=('post', 'content', 'user_id')
		widgets = {
			'post': forms.HiddenInput(),
			'user_id': forms.HiddenInput(),
		}

FreeSky/social/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.http.request import QueryDict
from django.views.generic import View, ListView
from user.models import User
from social.models import Article, Note
from social.forms import CommentNoteForm, SearchArticleForm
from social.services.notes_sort import PopularitySort


class ContentPreviewsView(ListView):
	model = Article
	paginate_by = 8
	pop_strategy = {
		'likes': PopularitySort.like_sorting,
		'views': PopularitySort.views_sorting,
		'popularity': PopularitySort.popularity_sorting,
	}
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search_form'] = SearchArticleForm(initial=self.search_params)
		return context

	def get_text_filter(self, text, queryset):
		text_set = text.strip().split(';')
		for i in text_set:
			if i[0] == '#':
				queryset = queryset.filter(tags=i)
			else:
				queryset = queryset.filter(title__icontains=i)
		return queryset

	def get_queryset(self):
		self.search_params = {key: self.request.GET.get(key, '').strip() for key in SearchArticleForm.keys()}
		queryset = Article.objects.all()
		if self.search_params['author'] == 'all':
			pass
		elif self.search_params['author'] == 'user':
			queryset = queryset.exclude(adminarticle__isnull=False)
		elif self.search_params['author'] == 'admin':
			queryset = queryset.filter(adminarticle__isnull=False)
		if self.search_params['text']:
			queryset = self.get_text_filter(self.search_params['text'], queryset)
		if self.search_params['location']:
			queryset = queryset.filter(location__name=self.search_params['location'])
		if self.search_params['publish_time']:
			queryset = queryset.order_by(self.search_params['publish_time'])
		if self.search_params['populatity']:
			queryset = self.pop_strategy[self.search_params['populatity']](queryset)
		return queryset

class ContentView(View):
	template_name = 'social/note.html'

	def get(self, request, note_pk):
		back_url = request.GET.get('next', '/')
		note = get_object_or_404(Article, pk=note_pk)
		context = {
			'note':note,
			'back_url': back_url,
		}
		return render(request, self.template_name, context)
	
	def post(self, request, note_pk):
		form = CommentNoteForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		return redirect(f'{request.get_full_path()}#{form.data["post"]}')

class CreateContentNote(View):
	form_class = CommentNoteForm
	success_url = 'social/'
	template_name = ''

	def get(self, request):
		user = User.objects.values('email').get(pk=request.user)
		form = self.form_class(initial={'user': user['email']})
		context = {
			'form': form,
		}
		return render(request, 'social/new_note.html', context)


class DeleteContentNote(View):
	success_url = '/'
	# form_class = DeletionCheckForm

	def get(self, request, note_pk):
		note = get_object_or_404(Note, pk=note_pk, user_id=request.user)
		note.delete()
		return redirect(request.GET.get('next', self.success_url))

FreeSky/templates/social/article_list.html
{%extends 'layout/base.html'%}
{% load static %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'social/css/note_list.css' %}">
{% endblock style %}
{% block content %}
<main class="_main">
	<div class="main-block _container">
		<form method="get">
		{{search_form}}
		<button>Поиск</button>
		</form>
		<div class="main-block__content-block">
			<h1>Articles</h1>
			<ul class="main-block__content-list content-list">
				{% for article in object_list %}
					<li class="content-item">
						<h3 class="title-content">{{ article.title }}</h3>
						{% if article.preview_image %}
						<div class="content-item__img">
							<div class="background"></div>
							<img class="_ibg" src="{{article.preview_image.url}}" alt="logo">
						</div> 
						{% endif %}
						<a class="content-item__a" href="
						{% if article.adminarticle %}
						{{ article.adminarticle.get_absolute_url }}
						{% else %}{{ article.get_absolute_url }}{% endif %}?next={{ request.path }}"> Подробнее >> </a>
						<div class="content-item__utility">
							<ul class="utility-list">
								<li class="licon icon-like">
									<img src="{% static 'media/images/default/heart.svg' %}" height="20px" width="20px">
									<a href="#">{{article.likes.count}}</a>
								</li>
								<li class="licon icon-view">
									<img src="{% static 'media/images/default/views.svg' %}" height="20px" width="20px">
									<a href="#">{{article.views.count}}</a></li>
								<li class="licon icon-com">
									<img src="{% static 'media/images/default/comment.svg' %}" height="20px" width="20px"> 
									<a href="#">{{article.note_comment_set.count}}</a>
								</li>
								{% if article.tags.all %}
									<li class="licon icon-tags">
										<img src="{% static 'media/images/default/tag.svg' %}" height="20px" width="20px">
									</li>
									{% for tag in article.tags.all %}
										<li class="licon icon-tags">
											<a href="?text={{tag.name|urlencode}}">{{tag}}</a>
										</li>
									{% endfor %}
								{% endif %}
								{% if article.location.all %}
									<li class="licon icon-tags">
										<img src="{% static 'media/images/default/location.svg' %}" height="20px" width="20px">
									</li>
									{% for location in article.location.all %}
										<li class="licon icon-tags">
											<a href="?location={{location}}">{{location}}</a>
										</li>
									{% endfor %}
								{% endif %}
							</ul>
						</div>
						<div class="licon dat">{{ article.publish_date|date }}</div>
					</li>
				{% empty %}
					<li>No articles yet.</li>
				{% endfor %}
			</ul>
			<div class="pagination">
				<span class="step-links">
					{% if page_obj.has_previous %}
						<a href="?page=1">&laquo; first</a>
						<a href="?page={{ page_obj.previous_page_number }}">previous</a>
					{% endif %}
			
					<span class="current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
			
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">next</a>
						<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					{% endif %}
				</span>
			</div>
		</div>
	</div>
</main>
{% endblock %}



FreeSky/templates/social/comments.html
{% load static %}
{% load contentnote_tags %}
{% for comment in note.note_comment_set.all %}
	<a name="#{{comment.pk}}">
		{{comment.get_author}} {{ comment.publish_date|date }}
	<p>
	{% if author %}<a href="#{{note.pk}}" name="{{sub_comment.pk}}">{{note.get_author}}</a>,{% endif %} {{comment.content|safe}}
	</p>
	<div class="comment-head">
		<img id="{{comment.pk}}" class="note-views" src="{% static 'media/images/default/views.svg' %}" weight="30" height="30" aria-label="Просмотры" alt="Просмотры"/><div class="views-value">{{comment.views.count}}</div>
		<img id="{{comment.pk}}" class="note-likes" src="{% static 'media/images/default/heart.svg' %}" weight="30" height="30" aria-label="Лайки" alt="Лайки"/><div class="likes-value">{{comment.likes.count}}</div> 
		<a href="#" class="response-note" id="{{comment.pk}}">Ответить</a>
	</div>
	{% get_comments request=request note=comment author=True verbose_empty=False %}	
{% empty %}
	{% if verbose_empty %}
	<p>Комментариев нет</p>
	{% endif %}
{% endfor %}

FreeSky/templates/social/new_note.html
{% load static %}
<form method='POST' enctype="multipart/form-data" class="newnote-form">
	{% csrf_token %}
	{{form.media}}
	{{form}}
	<button id="note-button" type="submit" class="_button" name="form" value="{{form.form_name}}?{{note_pk}}">Отправить</button>
</form>

FreeSky/templates/social/note.html
{%extends 'layout/base.html'%}
{% load static %}
{% load contentnote_tags %}
{% block style %}
	{{block.super}}
	<link rel="stylesheet" href="{% static 'social/css/note.css' %}">
{% endblock %}
{% block content %}
<main class="_main">
	<div class="main-block _container">
		<div class="main-block__content-block">
			<h1>{{ note.title }}</h1>
			{% if note.adminarticle %}
			{{note.adminarticle.get_author}}, {{ note.publish_date|date }}<br>
			{% else %}
			{{note.get_author}}, {{ note.publish_date|date }}<br>
			{% endif %}

			<div class="main-block__content-list content-list">
				<div class="content-item">
					{{note.content|safe}}
				</div>
				<a href="{{back_url}}"> << Назад </a>
			</div>
		</div>
		<div class="comments">
			<div class="comment-head">
				<img id="{{note.pk}}" class="note-views" src="{% static 'media/images/default/views.svg' %}" weight="30" height="30" aria-label="Просмотры" alt="Просмотры"/><div class="views-value">{{note.views.count}}</div>
				<img id="{{note.pk}}" class="note-likes" src="{% static 'media/images/default/heart.svg' %}" weight="30" height="30" aria-label="Лайки" alt="Лайки"/><div class="likes-value">{{note.likes.count}}</div> 
				<a href="#" class="response-note" id="{{note.pk}}">Комментировать</a>
			</div>
			<div class="comment-list">
				<h3>Комментарии:</h3>
				{% get_comments request=request note=note author=False verbose_empty=True %}
			</div>
		</div>
	</div>
</main>
<div id="response-form-div" hidden>
	{% create_comment_note request note.pk %}
</div>
{% endblock %}
{% block scripts %}
{{block.super}}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}" id="ckeditor-init-script"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'social/js/note.js' %}"></script>
{{ user.pk|json_script:'user'}}
{{ request.COOKIES.sessionid|json_script:'session'}}
{% endblock %}

FreeSky/templates/social/short_preview.html
{% load static %}
<ul class="preview-list">
	{% for note in notes %}
		<div class="preview-item item">
			<div class="short-preview-image">
				<img  src="{{ note.preview_image.url }}" alt="logo">
			</div>
			<div class="item__main-info">
				<h5 class="profile-main-text">
					{{ note.title }}
				</h5>
				<p class="profile-sub-text">
					{{note.content|safe|truncatechars:15}}
				</p>
				<a class="profile-sub-text" href="{{ note.get_absolute_url }}?next={{ request.path }}"> 
					К статье >>
				</a>
			</div>
		</div>
	{% empty %}
		<p class="profile-sub-text">{{empty_message}}</p>
	{% endfor %}
</ul>

FreeSky/templates/social/user_short_preview.html
{% load static %}
<ul class="preview-list">
	{% for note in notes %}
		<div class="preview-item item">
			<div class="short-preview-image">
				<img  src="{{ note.preview_image.url }}" alt="logo">
			</div>
			<div class="item__main-info">
				<h5 class="profile-main-text">
					{{ note.title }}
				</h5>
				<p class="profile-sub-text">
					{{note.content|safe|truncatechars:15}}
				</p>
				<a class="profile-sub-text" href="{{ note.get_absolute_url }}?next={{ request.path }}"> 
					К статье >>
				</a>
			</div>
			<a href="?edit_note={{note.pk}}">
				<div class="icon_img">
					<img src="{% static 'media/images/default/edit.svg' %}" alt="edit">
				</div>
			</a>
			<a href="{{note.get_delete_url}}?next={{ request.path }}">
				<div class="icon_img">
					<img src="{% static 'media/images/default/bin.svg' %}" alt="delete">
				</div>
			</a>
		</div>
	{% empty %}
		<p class="profile-sub-text">{{empty_message}}</p>
	{% endfor %}
</ul>